package resource

import "go-soccer/core/domain"

var Players = []*domain.Player{
	{
		ID:       1,
		TeamID:   1,
		Name:     "Nor Halid",
		Number:   1,
		Position: "GK",
		Nation:   "IDN",
	},
	{
		ID:       2,
		TeamID:   1,
		Name:     "Bagas Kaffa",
		Number:   2,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       3,
		TeamID:   1,
		Name:     "Yuswanto Aditya",
		Number:   3,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       4,
		TeamID:   1,
		Name:     "Muhammad Helmi",
		Number:   4,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       5,
		TeamID:   1,
		Name:     "Carli de Murga",
		Number:   6,
		Position: "DF",
		Nation:   "PHI",
	},
	{
		ID:       6,
		TeamID:   1,
		Name:     "Makan Konate",
		Number:   7,
		Position: "MF",
		Nation:   "MLI",
	},
	{
		ID:       7,
		TeamID:   1,
		Name:     "Chris Rumbiak",
		Number:   8,
		Position: "MF",
		Nation:   "MF",
	},
	{
		ID:       8,
		TeamID:   1,
		Name:     "Gustavo Tocantins",
		Number:   11,
		Position: "BRA",
		Nation:   "FW",
	},
	{
		ID:       9,
		TeamID:   1,
		Name:     "Bayu Pradana",
		Number:   13,
		Position: "MF",
		Nation:   "IDN",
	},
	{
		ID:       10,
		TeamID:   1,
		Name:     "Nazar Nurzaidin",
		Number:   14,
		Position: "MF",
		Nation:   "IDN",
	},
	{
		ID:       11,
		TeamID:   1,
		Name:     "Rafi Syarahil",
		Number:   15,
		Position: "MF",
		Nation:   "IDN",
	},
	{
		ID:       12,
		TeamID:   2,
		Name:     "Rio Fahmi",
		Number:   2,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       13,
		TeamID:   2,
		Name:     "Dandi Maulana",
		Number:   5,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       14,
		TeamID:   2,
		Name:     "Tony Sucipto",
		Number:   6,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       15,
		TeamID:   2,
		Name:     "Ryo Matsumura",
		Number:   7,
		Position: "MF",
		Nation:   "JPN",
	},
	{
		ID:       16,
		TeamID:   2,
		Name:     "Syahrian Abimanyu",
		Number:   8,
		Position: "MF",
		Nation:   "IDN",
	},
	{
		ID:       17,
		TeamID:   2,
		Name:     "Marko Simic",
		Number:   9,
		Position: "FW",
		Nation:   "CRO",
	},
	{
		ID:       18,
		TeamID:   2,
		Name:     "Firza Andika",
		Number:   11,
		Position: "DF",
		Nation:   "IDN",
	},
	{
		ID:       19,
		TeamID:   2,
		Name:     "Adre Arido",
		Number:   13,
		Position: "GK",
		Nation:   "IDN",
	},
	{
		ID:       20,
		TeamID:   2,
		Name:     "Ondrej Kudela",
		Number:   17,
		Position: "DF",
		Nation:   "CZE",
	},
	{
		ID:       21,
		TeamID:   2,
		Name:     "Hanif Sjahbandi",
		Number:   19,
		Position: "MF",
		Nation:   "IDN",
	},
	{
		ID:       22,
		TeamID:   2,
		Name:     "Alfriyanto Nico",
		Number:   21,
		Position: "MF",
		Nation:   "IDN",
	},
}
